# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eauc_l1 <- function(beta, X, Y, silence) {
    .Call(`_AUCopt_eauc_l1`, beta, X, Y, silence)
}

varauc_l1 <- function(beta, X, Y) {
    .Call(`_AUCopt_varauc_l1`, beta, X, Y)
}

betaTOtheta <- function(beta) {
    .Call(`_AUCopt_betaTOtheta`, beta)
}

thetaTObeta <- function(theta) {
    .Call(`_AUCopt_thetaTObeta`, theta)
}

adjust_max <- function(beta) {
    .Call(`_AUCopt_adjust_max`, beta)
}

COVconvert <- function(theta, var) {
    .Call(`_AUCopt_COVconvert`, theta, var)
}

sauc_l1 <- function(beta, X, Y, cov) {
    .Call(`_AUCopt_sauc_l1`, beta, X, Y, cov)
}

dsauc_l1 <- function(beta, X, Y, cov) {
    .Call(`_AUCopt_dsauc_l1`, beta, X, Y, cov)
}

ddnormcpp <- function(x) {
    .Call(`_AUCopt_ddnormcpp`, x)
}

ddsauc_l1 <- function(beta, X, Y, cov) {
    .Call(`_AUCopt_ddsauc_l1`, beta, X, Y, cov)
}

vn_l1 <- function(beta, X, Y, cov) {
    .Call(`_AUCopt_vn_l1`, beta, X, Y, cov)
}

dn_l1 <- function(beta, X, Y, cov) {
    .Call(`_AUCopt_dn_l1`, beta, X, Y, cov)
}

newton_raphson_l1 <- function(beta0, tol, iteration, gamma, X, Y, var) {
    .Call(`_AUCopt_newton_raphson_l1`, beta0, tol, iteration, gamma, X, Y, var)
}

rcpparma_hello_world <- function() {
    .Call(`_AUCopt_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_AUCopt_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_AUCopt_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_AUCopt_rcpparma_bothproducts`, x)
}

